name: env1
channels:
  - anaconda
  - pytorch
  - plotly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=py310haa95532_0
  - aiofiles=22.1.0=py310haa95532_0
  - aiohappyeyeballs=2.4.0=py310haa95532_0
  - aiohttp=3.10.5=py310h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py310haa95532_0
  - anyio=4.6.2=py310haa95532_0
  - aom=3.6.0=hd77b12b_0
  - argcomplete=1.12.0=py_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310haa95532_0
  - attrs=24.2.0=py310haa95532_0
  - babel=2.11.0=py310haa95532_0
  - backports.zoneinfo=0.2.1=py310h5588dad_9
  - beautifulsoup4=4.12.3=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py310haa95532_0
  - blosc=1.21.3=h6c2663c_0
  - boost-cpp=1.74.0=h9f4b32c_8
  - boto3=1.36.3=py310haa95532_0
  - botocore=1.36.3=py310haa95532_0
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py310hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2024.12.31=haa95532_0
  - cachetools=5.3.3=py310haa95532_0
  - cairo=1.16.0=hc68a040_5
  - certifi=2025.1.31=py310haa95532_0
  - cffi=1.17.1=py310h827c3e9_0
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py310haa95532_0
  - cloudpickle=3.0.0=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - coloredlogs=15.0.1=py310haa95532_3
  - contourpy=1.2.0=py310h59b6b97_0
  - cryptography=43.0.3=py310h89fc84f_0
  - cuda-nvcc=12.4.131=0
  - cudatoolkit=11.6.0=hc0ea762_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.11=py310h827c3e9_1
  - cytoolz=0.12.2=py310h2bbff1b_0
  - dacite=1.7.0=pyhd8ed1ab_0
  - dask-core=2024.8.2=py310haa95532_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py310haa95532_0
  - dill=0.3.8=py310haa95532_0
  - dnspython=2.4.2=py310haa95532_0
  - eigen=3.4.0=h59b6b97_0
  - einops=0.8.1=pyhd8ed1ab_0
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5da7b33_0
  - fastapi=0.115.6=pyhd8ed1ab_0
  - fastapi-cli=0.0.5=pyhd8ed1ab_1
  - ffmpeg=4.2.2=he774522_0
  - ffmpy=0.3.0=pyhb6f538c_0
  - fiftyone=1.3.0=pyhd8ed1ab_0
  - fiftyone-brain=0.19.0=pyhd8ed1ab_0
  - filelock=3.13.1=py310haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.51.0=py310h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.5.0=py310h827c3e9_0
  - fsspec=2024.6.1=py310haa95532_0
  - ftfy=5.8=py_0
  - future=1.0.0=py310haa95532_0
  - giflib=5.2.2=h7edc060_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - glob2=0.7=pyhd3eb1b0_0
  - google-auth=2.29.0=py310haa95532_0
  - google-auth-oauthlib=0.5.2=py310haa95532_0
  - graphite2=1.3.14=hd77b12b_1
  - graphql-core=3.2.3=py310haa95532_1
  - grpcio=1.62.2=py310h5da7b33_0
  - gst-plugins-base=1.22.3=hfc3ed34_1
  - gstreamer=1.22.3=h1779075_1
  - h11=0.14.0=py310haa95532_0
  - h2=4.0.0=py310haa95532_3
  - h5py=3.12.1=py310h3b2c811_0
  - harfbuzz=4.4.1=h27de254_0
  - hdf5=1.12.1=h51c971a_3
  - hpack=4.0.0=py_0
  - httpcore=1.0.2=py310haa95532_0
  - httptools=0.6.4=py310h827c3e9_0
  - httpx=0.27.0=py310haa95532_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_1
  - humanfriendly=10.0=py310haa95532_2
  - humanize=3.10.0=pyhd3eb1b0_0
  - hypercorn=0.17.3=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=70.1=h0e60522_0
  - idna=3.7=py310haa95532_0
  - imagecodecs=2023.1.23=py310h6c6a46e_0
  - imageio=2.33.1=py310haa95532_0
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=py310haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - inflate64=0.3.1=py310h827c3e9_2
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py310haa95532_0
  - ipython=8.27.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.19.1=py310haa95532_0
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jmespath=1.0.1=py310haa95532_0
  - joblib=1.4.2=py310haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=py310haa95532_0
  - jsonlines=2.0.0=pyhd3eb1b0_2
  - jsonschema=4.23.0=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_core=5.7.2=py310haa95532_0
  - jupyter_events=0.10.0=py310haa95532_0
  - jupyter_server=2.14.1=py310haa95532_0
  - jupyter_server_terminals=0.4.4=py310haa95532_1
  - jupyterlab=3.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=py310haa95532_0
  - jupyterlab_server=2.27.3=py310haa95532_0
  - kaleido-core=0.2.1=h2bbff1b_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libaec=1.0.4=h33f27b4_1
  - libavif=0.11.1=h2bbff1b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.78.4=ha17d25a_0
  - libgrpc=1.62.2=hf25190f_0
  - libiconv=1.16=h2bbff1b_3
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.0=h70ee33d_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libsqlite=3.48.0=h67fdade_1
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.1=h24da03e_2
  - libzlib=1.2.13=h2466b09_6
  - libzopfli=1.0.3=ha925a31_0
  - locket=1.0.0=py310haa95532_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown=3.4.1=py310haa95532_0
  - markdown-it-py=2.2.0=py310haa95532_1
  - markupsafe=2.1.3=py310h2bbff1b_0
  - mathjax=2.7.5=haa95532_0
  - matplotlib=3.9.2=py310haa95532_0
  - matplotlib-base=3.9.2=py310he19b0ae_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mdurl=0.1.0=py310haa95532_0
  - mistune=2.0.4=py310haa95532_0
  - mizani=0.13.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - monai=1.4.0=pyhd8ed1ab_1
  - mongodb=6.0.1=h3875601_0
  - mongoengine=0.29.1=pyhd8ed1ab_2
  - motor=3.5.1=pyhd8ed1ab_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpmath=1.3.0=py310haa95532_0
  - mrcfile=1.5.4=pyhd8ed1ab_0
  - multidict=6.1.0=py310h827c3e9_0
  - multivolumefile=0.2.3=pyhd3eb1b0_0
  - nbclassic=0.4.5=pyhd8ed1ab_0
  - nbclient=0.8.0=py310haa95532_0
  - nbconvert=7.16.4=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.3=py310haa95532_0
  - notebook=6.5.1=pyha770c72_0
  - notebook-shim=0.2.3=py310haa95532_0
  - numexpr=2.10.1=py310h4cd664f_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - oauthlib=3.2.2=py310haa95532_0
  - onnx=1.17.0=py310hf91db99_0
  - onnxruntime=1.20.1=py310h547b498_0
  - opencv=4.10.0=py310hd762f8c_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.15=h827c3e9_0
  - orjson=3.10.7=py310h827c3e9_0
  - overrides=7.4.0=py310haa95532_0
  - packaging=24.1=py310haa95532_0
  - pandas=2.2.3=py310hb4db72f_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py310haa95532_0
  - patsy=0.5.6=py310haa95532_0
  - pcre=8.45=hd77b12b_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.0.0=py310hb5480e2_0
  - pip=24.2=py310haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - plotly=5.15.0=py_0
  - plotnine=0.14.5=pyhd8ed1ab_0
  - ply=3.11=py310haa95532_0
  - pprintpp=0.4.0=pyhd8ed1ab_6
  - priority=1.3.0=py310haa95532_0
  - proglog=0.1.10=pyhaa61c55_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py310h958608f_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py7zr=0.20.5=py310haa95532_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybcj=1.0.1=py310h827c3e9_2
  - pycocotools=2.0.8=py310hb0944cc_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycryptodomex=3.21.0=py310h827c3e9_1
  - pydantic=2.8.2=py310haa95532_0
  - pydantic-core=2.20.1=py310hefb1915_0
  - pydash=8.0.5=pyhd8ed1ab_0
  - pydub=0.25.1=pyhd8ed1ab_0
  - pygments=2.15.1=py310haa95532_1
  - pyjwt=2.9.0=py310haa95532_0
  - pymongo=4.8.0=py310h827c3e9_0
  - pyopenssl=24.2.1=py310haa95532_0
  - pyparsing=3.2.0=py310haa95532_0
  - pyppmd=1.0.0=py310hd77b12b_0
  - pyqt=5.15.10=py310hd77b12b_0
  - pyqt5-sip=12.13.0=py310h2bbff1b_0
  - pyreadline3=3.4.1=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.15=h4607a30_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-dotenv=0.21.0=py310haa95532_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-flatbuffers=24.3.25=py310haa95532_0
  - python-json-logger=2.0.7=py310haa95532_0
  - python-kaleido=0.2.1=py310haa95532_0
  - python-multipart=0.0.19=pyhff2d567_1
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=py3.10_cuda11.6_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310haa95532_0
  - pywavelets=1.7.0=py310h827c3e9_0
  - pywin32=305=py310h2bbff1b_0
  - pywinpty=2.0.10=py310h5da7b33_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=25.1.2=py310hd77b12b_0
  - pyzstd=0.16.2=py310h4fc1ca9_0
  - qt-main=5.15.8=h720456b_6
  - rarfile=4.0=pyh9f0ad1d_0
  - re2=2022.04.01=hd77b12b_0
  - referencing=0.30.2=py310haa95532_0
  - regex=2024.11.6=py310h827c3e9_0
  - requests=2.32.3=py310haa95532_1
  - requests-oauthlib=2.0.0=py310haa95532_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rich=13.9.4=py310haa95532_0
  - rpds-py=0.10.6=py310h062c2fa_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=1.0.1=py310h2eaa2aa_0
  - ruff=0.3.5=py310h8ecf97c_1
  - s3transfer=0.11.2=py310haa95532_0
  - safehttpx=0.1.6=pyhd8ed1ab_1
  - scikit-image=0.19.2=py310h4ed8f06_0
  - scikit-learn=1.0.2=py310h4ed8f06_0
  - scipy=1.14.1=py310h8640f81_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - semantic_version=2.8.5=pyhd3eb1b0_0
  - send2trash=1.8.2=py310haa95532_0
  - setuptools=75.1.0=py310haa95532_0
  - shellingham=1.5.0=py310haa95532_0
  - sip=6.7.12=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6c2663c_1
  - sniffio=1.3.0=py310haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - sse-starlette=0.10.3=pyhd8ed1ab_0
  - sseclient-py=1.8.0=pyhd8ed1ab_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - starlette=0.41.3=pyha770c72_1
  - statsmodels=0.14.2=py310h827c3e9_0
  - strawberry-graphql=0.260.2=pyh29332c3_0
  - submitit=1.5.2=pyhd8ed1ab_0
  - sympy=1.13.3=pyh04b8f61_5
  - tabulate=0.9.0=py310haa95532_0
  - taskgroup=0.0.0a4=pyhd8ed1ab_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=9.0.0=py310haa95532_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310haa95532_1
  - terminado=0.17.1=py310haa95532_0
  - texttable=1.6.4=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py310h9909e9c_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tomli=2.0.1=py310haa95532_0
  - tomlkit=0.13.2=py310haa95532_0
  - toolz=0.12.0=py310haa95532_0
  - torchaudio=0.12.1=py310_cu116
  - torchvision=0.13.1=py310_cu116
  - tornado=6.4.1=py310h827c3e9_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.14.3=py310haa95532_0
  - typer=0.15.1=pyhd8ed1ab_0
  - typer-slim=0.15.1=pyhd8ed1ab_0
  - typer-slim-standard=0.15.1=hd8ed1ab_0
  - typing-extensions=4.11.0=py310haa95532_0
  - typing_extensions=4.11.0=py310haa95532_0
  - tzdata=2024b=h04d1e81_0
  - tzlocal=5.2=py310haa95532_0
  - ucrt=10.0.20348.0=haa95532_0
  - unicodedata2=15.1.0=py310h2bbff1b_0
  - universal-analytics-python3=1.1.1=pyhd8ed1ab_1
  - urllib3=2.2.3=py310haa95532_0
  - uvicorn=0.32.1=py310haa95532_0
  - uvicorn-standard=0.32.1=py310haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.42.34433=h6356254_24
  - voxel51-eta=0.14.0=pyhd8ed1ab_0
  - vs2015_runtime=14.42.34433=hfef2bbc_24
  - watchfiles=0.24.0=py310h636fa0f_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=1.8.0=py310haa95532_0
  - websockets=10.4=py310h2bbff1b_1
  - werkzeug=3.0.6=py310haa95532_0
  - wheel=0.44.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winpty=0.4.3=4
  - wrapt=1.17.0=py310h827c3e9_0
  - wsproto=1.2.0=py310haa95532_0
  - xmltodict=0.14.2=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.7.0=hd77b12b_1
  - yarl=1.11.0=py310h827c3e9_0
  - zeromq=4.3.5=hd77b12b_0
  - zfp=1.0.0=hd77b12b_0
  - zipp=3.20.2=py310haa95532_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - astropy==5.1.1
      - comm==0.2.2
      - gradio==5.9.1
      - gradio-client==1.5.2
      - ipywidgets==8.1.2
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.10
      - platformdirs==4.2.0
      - poppy==1.0.3
      - pyerfa==2.0.0.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - randomcolor==0.4.4.6
      - session-info==1.0.0
      - shapely==2.0.1
      - shareloc-utils==0.1.10
      - stdlib-list==0.8.0
      - storm-analysis==2.2
      - tifffile==2024.2.12
      - widgetsnbextension==4.0.10
      - xlrd==2.0.1
prefix: C:\Users\dafei.xiao\Miniconda3\envs\env1
